# Generated by Django 4.2.13 on 2024-07-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tipo',
            field=models.CharField(choices=[('bodeguero', 'Bodeguero'), ('cliente', 'Cliente'), ('admin', 'Admin')], default='cliente', max_length=10),
        ),
    ]
