# Generated by Django 4.2.13 on 2024-07-09 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_cart_pedido_pedidoitem_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoitem',
            name='producto',
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='cart_item',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='App.cartitem'),
        ),
    ]
