# Generated by Django 4.2.13 on 2024-07-09 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_remove_pedidoitem_producto_pedido_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitem',
            name='cart_item',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='App.cartitem'),
        ),
    ]
