# Generated by Django 4.2.13 on 2024-07-09 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_pedidoitem_cart_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitem',
            name='cart_item',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.cartitem'),
        ),
    ]
